"""FRED constants for external reference-rate observations."""

from __future__ import annotations

FRED_API_BASE_URL = "https://api.stlouisfed.org/fred"
FRED_API_KEY_SECRET_NAME = "FRED_API_KEY"

US_TREASURY_CMT_2Y_INDEX_IDENTIFIER = "US_TREASURY_CMT_2Y"
US_TREASURY_CMT_5Y_INDEX_IDENTIFIER = "US_TREASURY_CMT_5Y"
US_TREASURY_CMT_10Y_INDEX_IDENTIFIER = "US_TREASURY_CMT_10Y"
US_TREASURY_CMT_30Y_INDEX_IDENTIFIER = "US_TREASURY_CMT_30Y"
FED_FUNDS_TARGET_UPPER_INDEX_IDENTIFIER = "FED_FUNDS_TARGET_UPPER"

FRED_REFERENCE_RATE_INDEX_IDENTIFIERS = (
    US_TREASURY_CMT_2Y_INDEX_IDENTIFIER,
    US_TREASURY_CMT_5Y_INDEX_IDENTIFIER,
    US_TREASURY_CMT_10Y_INDEX_IDENTIFIER,
    US_TREASURY_CMT_30Y_INDEX_IDENTIFIER,
    FED_FUNDS_TARGET_UPPER_INDEX_IDENTIFIER,
)

__all__ = [
    "FED_FUNDS_TARGET_UPPER_INDEX_IDENTIFIER",
    "FRED_API_BASE_URL",
    "FRED_API_KEY_SECRET_NAME",
    "FRED_REFERENCE_RATE_INDEX_IDENTIFIERS",
    "US_TREASURY_CMT_10Y_INDEX_IDENTIFIER",
    "US_TREASURY_CMT_2Y_INDEX_IDENTIFIER",
    "US_TREASURY_CMT_30Y_INDEX_IDENTIFIER",
    "US_TREASURY_CMT_5Y_INDEX_IDENTIFIER",
]
