"""Banxico SIE constants for Mexican reference-rate fixings."""

from __future__ import annotations

BANXICO_SIE_BASE_URL = "https://www.banxico.org.mx/SieAPIRest/service/v1"
BANXICO_TOKEN_SECRET_NAME = "BANXICO_TOKEN"
BANXICO_POLICY_TARGET_INDEX_IDENTIFIER = "BANXICO_POLICY_TARGET"

TIIE_OVERNIGHT_INDEX_IDENTIFIER = "TIIE_OVERNIGHT"
TIIE_28_INDEX_IDENTIFIER = "TIIE_28"
TIIE_91_INDEX_IDENTIFIER = "TIIE_91"
TIIE_182_INDEX_IDENTIFIER = "TIIE_182"
CETE_28_INDEX_IDENTIFIER = "CETE_28"
CETE_91_INDEX_IDENTIFIER = "CETE_91"
CETE_182_INDEX_IDENTIFIER = "CETE_182"

BANXICO_FIXING_INDEX_IDENTIFIERS = (
    TIIE_OVERNIGHT_INDEX_IDENTIFIER,
    TIIE_28_INDEX_IDENTIFIER,
    TIIE_91_INDEX_IDENTIFIER,
    TIIE_182_INDEX_IDENTIFIER,
    CETE_28_INDEX_IDENTIFIER,
    CETE_91_INDEX_IDENTIFIER,
    CETE_182_INDEX_IDENTIFIER,
)
