"""migration

Revision ID: 0001
Revises: 
Create Date: 2026-06-10 22:39:30.998365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valmer_connectors__valmerassetdetails',
    sa.Column('asset_uid', sa.Uuid(), nullable=False),
    sa.Column('valmer_unique_identifier', sa.String(length=255), nullable=False),
    sa.Column('details_asof', sa.DateTime(timezone=True), nullable=True),
    sa.Column('security_type', sa.String(length=64), nullable=True),
    sa.Column('issuer', sa.String(length=128), nullable=True),
    sa.Column('series', sa.String(length=128), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('issued_amount', sa.Float(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('issue_term', sa.Float(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('face_value', sa.Float(), nullable=True),
    sa.Column('issue_currency', sa.String(length=32), nullable=True),
    sa.Column('underlying', sa.String(length=255), nullable=True),
    sa.Column('placement_yield', sa.Float(), nullable=True),
    sa.Column('placement_spread', sa.Float(), nullable=True),
    sa.Column('coupon_frequency', sa.String(length=64), nullable=True),
    sa.Column('coupon_rate', sa.Float(), nullable=True),
    sa.Column('coupon_rule', sa.String(length=255), nullable=True),
    sa.Column('coupons_at_issue', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_uid'], ['ms_markets__asset.uid'], name=op.f('fk__valmer_connectors__valmerassetdetails__asset_uid_cc247d13d3'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_uid', name=op.f('pk__valmer_connectors__valmerassetdetails')),
    info={'namespace': 'valmer_connectors', 'identifier': 'valmer_connectors.ValmerAssetDetails', 'markets_storage_app': 'valmer_connectors'}
    )
    op.create_index(op.f('ix__valmer_connectors__valmerassetdetails__issuer'), 'valmer_connectors__valmerassetdetails', ['issuer'], unique=False)
    op.create_index(op.f('ix__valmer_connectors__valmerassetdetails__maturity_date'), 'valmer_connectors__valmerassetdetails', ['maturity_date'], unique=False)
    op.create_index(op.f('uix__valmer_connectors__valmerassetdetails__valmer_u_b26f4d8531'), 'valmer_connectors__valmerassetdetails', ['valmer_unique_identifier'], unique=True)
    op.create_table('valmer_connectors__vector_de_precios_valmer',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_identifier', sa.String(length=255), nullable=False),
    sa.Column('valuation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clean_price', sa.Float(), nullable=True),
    sa.Column('dirty_price', sa.Float(), nullable=True),
    sa.Column('accrued_interest', sa.Float(), nullable=True),
    sa.Column('current_coupon', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('amount_outstanding', sa.Float(), nullable=True),
    sa.Column('days_since_coupon', sa.Float(), nullable=True),
    sa.Column('coupons_remaining', sa.Float(), nullable=True),
    sa.Column('market_event', sa.String(), nullable=True),
    sa.Column('uh_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('theoretical_price', sa.Float(), nullable=True),
    sa.Column('posted_bid', sa.Float(), nullable=True),
    sa.Column('posted_ask', sa.Float(), nullable=True),
    sa.Column('bid_yield', sa.Float(), nullable=True),
    sa.Column('ask_yield', sa.Float(), nullable=True),
    sa.Column('bid_spread', sa.Float(), nullable=True),
    sa.Column('ask_spread', sa.Float(), nullable=True),
    sa.Column('moodys_rating', sa.String(), nullable=True),
    sa.Column('sp_rating', sa.String(), nullable=True),
    sa.Column('marketability', sa.String(), nullable=True),
    sa.Column('liquidity', sa.Float(), nullable=True),
    sa.Column('daily_change_pct', sa.Float(), nullable=True),
    sa.Column('weekly_change_pct', sa.Float(), nullable=True),
    sa.Column('max_price_12m', sa.Float(), nullable=True),
    sa.Column('min_price_12m', sa.Float(), nullable=True),
    sa.Column('suspension_status', sa.String(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('volatility_secondary', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('monetary_duration', sa.Float(), nullable=True),
    sa.Column('convexity', sa.Float(), nullable=True),
    sa.Column('value_at_risk', sa.Float(), nullable=True),
    sa.Column('standard_deviation', sa.Float(), nullable=True),
    sa.Column('adjusted_face_value', sa.Float(), nullable=True),
    sa.Column('fitch_rating', sa.String(), nullable=True),
    sa.Column('max_price_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_price_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sensitivity', sa.Float(), nullable=True),
    sa.Column('macaulay_duration', sa.Float(), nullable=True),
    sa.Column('yield_rate', sa.Float(), nullable=True),
    sa.Column('hr_rating', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_identifier'], ['ms_markets__asset.unique_identifier'], name=op.f('fk__valmer_connectors__vector_de_precios_valmer__ass_e5609252cb'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'valmer_connectors', 'namespace': 'valmer_connectors', 'identifier': 'valmer_connectors.vector_de_precios_valmer'}
    )
    op.create_index('uix__valmer_connectors__vector_de_precios_valmer__ti_bc46a1b669', 'valmer_connectors__vector_de_precios_valmer', ['time_index', 'asset_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix__valmer_connectors__vector_de_precios_valmer__ti_bc46a1b669', table_name='valmer_connectors__vector_de_precios_valmer')
    op.drop_table('valmer_connectors__vector_de_precios_valmer')
    op.drop_index(op.f('uix__valmer_connectors__valmerassetdetails__valmer_u_b26f4d8531'), table_name='valmer_connectors__valmerassetdetails')
    op.drop_index(op.f('ix__valmer_connectors__valmerassetdetails__maturity_date'), table_name='valmer_connectors__valmerassetdetails')
    op.drop_index(op.f('ix__valmer_connectors__valmerassetdetails__issuer'), table_name='valmer_connectors__valmerassetdetails')
    op.drop_table('valmer_connectors__valmerassetdetails')
    # ### end Alembic commands ###
