"""migration

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-19 16:17:27.624737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valmer_connectors__vector_de_precios_valmer', 'low')
    op.drop_column('valmer_connectors__vector_de_precios_valmer', 'open')
    op.drop_column('valmer_connectors__vector_de_precios_valmer', 'open_time')
    op.drop_column('valmer_connectors__vector_de_precios_valmer', 'close')
    op.drop_column('valmer_connectors__vector_de_precios_valmer', 'volume')
    op.drop_column('valmer_connectors__vector_de_precios_valmer', 'high')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valmer_connectors__vector_de_precios_valmer', sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('valmer_connectors__vector_de_precios_valmer', sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('valmer_connectors__vector_de_precios_valmer', sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('valmer_connectors__vector_de_precios_valmer', sa.Column('open_time', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('valmer_connectors__vector_de_precios_valmer', sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('valmer_connectors__vector_de_precios_valmer', sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
