"""cut over daily index values

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-19 17:52:07.475303

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ms_markets__index_values__t_1d',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('index_identifier', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('definition_uid', sa.Uuid(), nullable=True),
    sa.Column('observation_status', sa.String(length=32), nullable=True),
    sa.Column('source_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['definition_uid'], ['ms_markets__indexcalculationdefinition.uid'], name=op.f('fk__ms_markets__index_values__t_1d__definition_uid_5b419a5d21'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['index_identifier'], ['ms_markets__index.unique_identifier'], name=op.f('fk__ms_markets__index_values__t_1d__index_identifier_1fe142575d'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'ms_markets', 'namespace': 'mainsequence.markets', 'identifier': 'IndexValuesTS'}
    )
    op.create_index('ix__ms_markets__index_values__t_1d__definition_uid', 'ms_markets__index_values__t_1d', ['definition_uid'], unique=False)
    op.create_index('ix__ms_markets__index_values__t_1d__observation_status', 'ms_markets__index_values__t_1d', ['observation_status'], unique=False)
    op.create_index('uix__ms_markets__index_values__t_1d__time_index__ind_88c17df072', 'ms_markets__index_values__t_1d', ['time_index', 'index_identifier'], unique=True)
    op.execute(
        sa.text(
            """
            INSERT INTO ms_markets__index_values__t_1d (
                time_index,
                index_identifier,
                value,
                unit,
                definition_uid,
                observation_status,
                source_as_of,
                metadata_json
            )
            SELECT
                time_index,
                index_identifier,
                rate,
                'decimal',
                NULL,
                'ready',
                time_index,
                json_build_object(
                    'migration_revision', 'valmer_connectors.0004',
                    'source_series_id', CASE index_identifier
                        WHEN 'US_TREASURY_CMT_2Y' THEN 'DGS2'
                        WHEN 'US_TREASURY_CMT_5Y' THEN 'DGS5'
                        WHEN 'US_TREASURY_CMT_10Y' THEN 'DGS10'
                        WHEN 'US_TREASURY_CMT_30Y' THEN 'DGS30'
                        WHEN 'FED_FUNDS_TARGET_UPPER' THEN 'DFEDTARU'
                        WHEN 'BANXICO_POLICY_TARGET' THEN 'SF61745'
                    END,
                    'provider', CASE
                        WHEN index_identifier = 'BANXICO_POLICY_TARGET'
                            THEN 'Banco de Mexico'
                        ELSE 'FRED'
                    END
                )
            FROM valmer_connectors__reference_rate_observations
            ON CONFLICT (time_index, index_identifier) DO NOTHING
            """
        )
    )
    op.drop_index(
        'uix__valmer_connectors__reference_rate_observations_005d155688',
        table_name='valmer_connectors__reference_rate_observations',
    )
    op.drop_table('valmer_connectors__reference_rate_observations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valmer_connectors__reference_rate_observations',
    sa.Column('time_index', sa.DateTime(timezone=True), nullable=False),
    sa.Column('index_identifier', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['index_identifier'], ['ms_markets__index.unique_identifier'], name=op.f('fk__valmer_connectors__reference_rate_observations_f92f29a6a3'), ondelete='RESTRICT'),
    info={'markets_storage_app': 'valmer_connectors', 'namespace': 'valmer_connectors', 'identifier': 'valmer_connectors.reference_rate_observations'}
    )
    op.create_index('uix__valmer_connectors__reference_rate_observations_005d155688', 'valmer_connectors__reference_rate_observations', ['time_index', 'index_identifier'], unique=True)
    op.execute(
        sa.text(
            """
            INSERT INTO valmer_connectors__reference_rate_observations (
                time_index,
                index_identifier,
                rate
            )
            SELECT time_index, index_identifier, value
            FROM ms_markets__index_values__t_1d
            WHERE index_identifier IN (
                'US_TREASURY_CMT_2Y',
                'US_TREASURY_CMT_5Y',
                'US_TREASURY_CMT_10Y',
                'US_TREASURY_CMT_30Y',
                'FED_FUNDS_TARGET_UPPER',
                'BANXICO_POLICY_TARGET'
            )
            """
        )
    )
    op.drop_index('uix__ms_markets__index_values__t_1d__time_index__ind_88c17df072', table_name='ms_markets__index_values__t_1d')
    op.drop_index('ix__ms_markets__index_values__t_1d__observation_status', table_name='ms_markets__index_values__t_1d')
    op.drop_index('ix__ms_markets__index_values__t_1d__definition_uid', table_name='ms_markets__index_values__t_1d')
    op.drop_table('ms_markets__index_values__t_1d')
    # ### end Alembic commands ###
