from src.instruments.curve_bootstrap import (
    CETE_182_INDEX_UNIQUE_IDENTIFIER,
    CETE_28_INDEX_UNIQUE_IDENTIFIER,
    CETE_91_INDEX_UNIQUE_IDENTIFIER,
    TIIE_182_INDEX_UNIQUE_IDENTIFIER,
    TIIE_28_INDEX_UNIQUE_IDENTIFIER,
    TIIE_91_INDEX_UNIQUE_IDENTIFIER,
    TIIE_OVERNIGHT_INDEX_UNIQUE_IDENTIFIER,
)

PROJECT_BUCKET_NAME = "Data Connectors"
BUCKET_NAME_HISTORICAL_VECTORS = "Hitorical Valmer Vector Analytico"
SUBYACENTE_TO_INDEX_MAP = {
    "TIIE28": TIIE_28_INDEX_UNIQUE_IDENTIFIER,
    "TIIE182": TIIE_182_INDEX_UNIQUE_IDENTIFIER,
    "TIIE91": TIIE_91_INDEX_UNIQUE_IDENTIFIER,
    "TIIE28 EQUIV 182": TIIE_182_INDEX_UNIQUE_IDENTIFIER,
    "Tasa TIIE Fondeo 1D": TIIE_OVERNIGHT_INDEX_UNIQUE_IDENTIFIER,
    "CETE_28": CETE_28_INDEX_UNIQUE_IDENTIFIER,
    "CETE28": CETE_28_INDEX_UNIQUE_IDENTIFIER,
    "CETE182": CETE_182_INDEX_UNIQUE_IDENTIFIER,
    "Bonos M Bruta(Yield)": CETE_28_INDEX_UNIQUE_IDENTIFIER,
    "Fondeo Bancario": TIIE_OVERNIGHT_INDEX_UNIQUE_IDENTIFIER,
    "Tasa TIIE Fondeo 1D": TIIE_OVERNIGHT_INDEX_UNIQUE_IDENTIFIER,
    "IRMXP-FGub-28": CETE_28_INDEX_UNIQUE_IDENTIFIER,
    "IRMXP-FGub-91": CETE_91_INDEX_UNIQUE_IDENTIFIER,
    "AAA": TIIE_28_INDEX_UNIQUE_IDENTIFIER,
    "D1": TIIE_28_INDEX_UNIQUE_IDENTIFIER,
    "P8-X8": CETE_182_INDEX_UNIQUE_IDENTIFIER,
    "P12-X12": CETE_182_INDEX_UNIQUE_IDENTIFIER,
    "P4-X4": CETE_91_INDEX_UNIQUE_IDENTIFIER,
}
