"""migration

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-09 09:35:10.476280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uix__valmer_connectors__vector_de_precio_feb66c1145_e8430ba4f5'), table_name='valmer_connectors__vector_de_precio_feb66c1145__quence_examples')
    op.drop_constraint(op.f('fk__valmer_connectors__vector_de_precio_feb66c1145_9e7694d80d'), 'valmer_connectors__vector_de_precio_feb66c1145__quence_examples', type_='foreignkey')
    op.alter_column(
        'valmer_connectors__vector_de_precio_feb66c1145__quence_examples',
        'unique_identifier',
        new_column_name='asset_identifier',
        existing_type=sa.String(length=255),
        existing_nullable=False,
    )
    op.create_foreign_key(op.f('fk__valmer_connectors__vector_de_precio_feb66c1145_96e2f305e4'), 'valmer_connectors__vector_de_precio_feb66c1145__quence_examples', 'ms_markets__asset__mainsequence_examples', ['asset_identifier'], ['unique_identifier'], ondelete='RESTRICT')
    op.create_index('uix__valmer_connectors__vector_de_precio_feb66c1145_105345f8f7', 'valmer_connectors__vector_de_precio_feb66c1145__quence_examples', ['time_index', 'asset_identifier'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix__valmer_connectors__vector_de_precio_feb66c1145_105345f8f7', table_name='valmer_connectors__vector_de_precio_feb66c1145__quence_examples')
    op.drop_constraint(op.f('fk__valmer_connectors__vector_de_precio_feb66c1145_96e2f305e4'), 'valmer_connectors__vector_de_precio_feb66c1145__quence_examples', type_='foreignkey')
    op.alter_column(
        'valmer_connectors__vector_de_precio_feb66c1145__quence_examples',
        'asset_identifier',
        new_column_name='unique_identifier',
        existing_type=sa.String(length=255),
        existing_nullable=False,
    )
    op.create_foreign_key(op.f('fk__valmer_connectors__vector_de_precio_feb66c1145_9e7694d80d'), 'valmer_connectors__vector_de_precio_feb66c1145__quence_examples', 'ms_markets__asset__mainsequence_examples', ['unique_identifier'], ['unique_identifier'], ondelete='RESTRICT')
    op.create_index(op.f('uix__valmer_connectors__vector_de_precio_feb66c1145_e8430ba4f5'), 'valmer_connectors__vector_de_precio_feb66c1145__quence_examples', ['time_index', 'unique_identifier'], unique=True)
    # ### end Alembic commands ###
