"""migration

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-09 13:04:02.337423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valmer_connectors__vector_de_precio_feb66c1145__quence_examples', 'days_since_coupon',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('valmer_connectors__vector_de_precio_feb66c1145__quence_examples', 'coupons_remaining',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('valmer_connectors__vector_de_precio_feb66c1145__quence_examples', 'coupons_remaining',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('valmer_connectors__vector_de_precio_feb66c1145__quence_examples', 'days_since_coupon',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
